stages:
  - build

build:apk:
  stage: build
  image: thyrlian/android-sdk:latest
  only:
    - tags
  script:
    - apt-get update && apt-get install -y file make
    - echo "$KEYSTORE_BASE64" | base64 -d > shoppinglist.keystore
    - ./gradlew assembleRelease
  artifacts:
    paths:
      - app/build/outputs/apk/release/
